#! /bin/sh

sxhkd &
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           0 # 40

bspc config split_ratio           0.48 # 0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true

bspc config normal_border_color  "#2a2a2a"
bspc config focused_border_color "#ffffff"

bspc rule -a kakaotalk.exe state=floating
bspc rule -a *:*:KakaoTalkShadowWnd hidden=on
bspc rule -a *:*:KakaoTalkEdgeWnd hidden=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Steam desktop='^3'
# bspc rule -a discord desktop='^4'
