#!/bin/sh

# Fixes `loginctl suspend` resuming to black screen with nvidia cards.
# Ref: https://bugs.gentoo.org/693384

case "${1-}" in
    'pre')
        /usr/bin/nvidia-sleep.sh suspend
        ;;

    'post')
        /usr/bin/nvidia-sleep.sh resume &
        ;;
    *)
        exit 1
        ;;
esac
