#! /bin/bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe | perl -pe 's|[M,m]VGA-0.*?([M,m]DVI-I-1)|$1|g' > "$PANEL_FIFO" &
#/home/stephen/bin/bspct > "$PANEL_FIFO" &
bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
date +'S%H:%M %p' > "$PANEL_FIFO" &

. panel_colors

case "$flavor" in
	bar)
		#FONT_FAMILY='-*-terminus-medium-*-*-*-14-*-*-*-*-*-*-*,-*-stlarch-medium-*-normal-*-12-*-*-*-*-*-*-*'
		FONT_FAMILY='-*-stlarch-medium-*-normal-*-*-*-*-*-*-*-*-*,-*-termsyn-medium-*-*-*-14-*-*-*-*-*-*-*'
        cat "$PANEL_FIFO" | panel_bar | bar -p -g x$PANEL_HEIGHT -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
		;;
	dzen2)
		FONT_FAMILY='DejaVu Sans'
		FONT_SIZE=11
		cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
		;;
esac

wait
