#! /bin/sh

bspc config focused_border_color '#FF5500' # Do not exclude 's, will be commentized
bspc config normal_border_color '#0C0C0C'

bspc config border_width        1
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Google-chrome-stable desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Steam desktop=^9 floating=on
bspc rule -a 'Minecraft 1.7.10' desktop=^9 floating=on
bspc rule -a hl2_linux desktop=^9 fullscreen=on

panel &
